#!/usr/bin/python
import sys
port=int(sys.argv[1])
addr=('localhost',port)

from socket import * 
fd=socket(AF_INET,SOCK_STREAM,0)
fd.connect(addr)

import json
fd.sendall(json.dumps({'header':'submit','body':{'cmd':'sleep 100', 'fileo':'/tmp/testc'}}))
#fd.sendall(json.dumps({'header':'submit','body':{'cmd':'sleep 100', 'fileo':'/tmp/testc'}}))
#print json.dumps({'header':'route','body':{'route':('localhost',port), 'body':{'header':'submit','body':{'cmd':'sleep 100', 'fileo':'/tmp/testc'}}}})
#fd.sendall(json.dumps({'header':'route','body':{'route':('aerobook2',port), 'body':{'header':'submit','body':{'cmd':'sleep 100', 'fileo':'/tmp/testc'}}}}))
fd.sendall(json.dumps({'header':'query','body':{'abc':"bcd"}}))
fd.sendall(json.dumps({'header':'query','body':{'abc':"bcd"}}))
#fd.sendall(json.dumps({'header':'route','body':{'route':('aerobook',port), 'body': {'header':'query','body':{'abc':"bcd"}}}}))


#job={}
#job['name']='JM'
#job['id']='JID'
#job['cmd']='sleep 100'
#job['fileo']='/tmp/'+job['id']

#print json.dumps({'header':'route','body': {'route':('192.168.0.92',9004),'body':{'header':'submit','body':job}}})
#fd.sendall(json.dumps({'header':'route','body': {'route':('192.168.0.92',9004),'body':{'header':'submit','body':job}}}))

fd.shutdown(SHUT_WR)
print fd.recv(1024)
import time
#time.sleep(10)
fd.close()

